version: '3.9'

services:
  historic:
    build: .
    platform: linux/arm64
    env_file:
      - .env
    command: [ "./historic_events", "1050000", "1200000" ]

  stream:
    build: .
    platform: linux/arm64
    env_file:
      - .env
    command: [ "./stream_events" ]
